Repository rancher/rancher-turtles-e2e, pull requests merged in 2024-11, with the labels that each got.

#80 Bump ele-testhelpers to support v2.10-head and new location for v2.9-head
  tests/go.mod
  tests/go.sum
Labels: kind/enhancement

#81 Refactor FleetRepo check
  tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
Labels: kind/bug

#79 Bump k3s version to v1.30.6+k3s1
  .github/workflows/master-e2e.yaml
Labels: area/testing

#83 Update local provider versions
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Labels: kind/bug
