Repository rancher/rancher-turtles-e2e, pull requests merged in 2025-06, with the labels that each got.

#195 CAPV+REK2 SL Micro registration
  tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/values.yaml
  tests/assets/rancher-turtles-fleet-example/capv/rke2/clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capv/rke2/clusters/values.yaml
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/fixtures/capv-helm-values.yaml
Labels: kind/enhancement, area/ci, area/testing

#197 Azure kubeadm clusterclass test
  .github/workflows/master-e2e.yaml
  tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/.helmignore
  tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/Chart.yaml
  tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/templates/cluster.yaml
  tests/cypress/latest/e2e/unit_tests/capz_kubeadm_clusterclass.spec.ts
Labels: squad/qa

#206 Azure RKE2 v2Prov test
  .github/workflows/master-e2e.yaml
  tests/cypress/latest/e2e/unit_tests/capz_rke2_v2prov_cluster.spec.ts
  tests/cypress/latest/fixtures/azure-rke-config.yaml
  tests/cypress/latest/fixtures/azure-rke2-cluster.yaml
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
Labels: kind/enhancement, area/testing, squad/qa

#210 Bump fleetProviderVersion
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Labels: squad/qa
