Repository rancher/rancher-turtles-e2e, pull requests merged in 2025-07, with the labels that each got.

#212 Use multiple replica count for control plane and worker machines
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capv/kubeadm/class-clusters/values.yaml
  tests/assets/rancher-turtles-fleet-example/capz/kubeadm/class-clusters/fleet.yaml
  tests/cypress/latest/e2e/unit_tests/capa_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capa_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_kubeadm_clusterclass.spec.ts
Labels: squad/qa

#203 CAPV RKE2 kube-vip test
  .github/workflows/master-e2e.yaml
  tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capv/rke2/class-clusters/values.yaml
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/fixtures/capv-docker-auth-token-secret.yaml
  tests/cypress/latest/fixtures/capv-helm-values.yaml
  tests/cypress/latest/fixtures/capv-kube-vip-static-pod-toggle-job.yaml
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
Labels: area/ci, area/testing, squad/qa

#216 CAPV use main branch for fleet gitrepos
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
Labels: squad/qa

#219 Update CYPRESS_DOCKER image
  .github/workflows/master-e2e.yaml
Labels: kind/enhancement, squad/qa

#218 Use the common function importYAML
  tests/cypress/latest/e2e/unit_tests/capd_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_rke2_v2prov_cluster.spec.ts
  tests/cypress/latest/support/capz_support.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
Labels: squad/qa

#223 Remove registration-method variable from CAPZ
  tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/templates/cluster.yaml
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Labels: squad/qa

#229 Remove legacy clusters tests
  .github/workflows/master-e2e.yaml
  README.md
  tests/cypress/latest/cypress.config.ts
  tests/cypress/latest/e2e/capa_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/capd_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_v2prov_cluster.spec.ts
  tests/cypress/latest/e2e/first_connection.spec.ts
  tests/cypress/latest/e2e/legacy/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capa_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capa_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capz_aks_cluster.spec.ts
  tests/cypress/latest/e2e/menu.spec.ts
  tests/cypress/latest/e2e/providers_setup.spec.ts
  tests/cypress/latest/e2e/turtles_extension.spec.ts
  tests/cypress/latest/e2e/turtles_operator.spec.ts
  tests/cypress/latest/e2e/user.spec.ts
Labels: squad/qa

#228 Add and remove clusterclass fleet repo for all the capd tests
  tests/cypress/latest/e2e/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/capd_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
Labels: squad/qa

#233 Refactor CAPD scaling tests
  tests/assets/rancher-turtles-fleet-example/capd/kubeadm/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capd/kubeadm/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/templates/cluster.yaml
  tests/cypress/latest/e2e/capd_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/fixtures/capd-helm-values.yaml
Labels: area/testing, squad/qa

#239 Add scaling tests for cloud providers
  .github/workflows/master-e2e.yaml
  tests/cypress/latest/e2e/azure_rke2_v2prov_cluster.spec.ts
  tests/cypress/latest/e2e/capa_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/legacy/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capv_rke2_cluster.spec.ts
  tests/cypress/latest/fixtures/aws/capa-aws-cluster-identity.yaml
  tests/cypress/latest/fixtures/aws/capa-kubeadm-class-cluster.yaml
  tests/cypress/latest/fixtures/aws/capa-rke2-class-cluster.yaml
  tests/cypress/latest/fixtures/aws/capi-aws-provider.yaml
  tests/cypress/latest/fixtures/azure/azure-rke-config.yaml
  tests/cypress/latest/fixtures/azure/azure-rke2-cluster.yaml
  tests/cypress/latest/fixtures/azure/capi-azure-provider.yaml
  tests/cypress/latest/fixtures/azure/capz-aks-class-cluster.yaml
  tests/cypress/latest/fixtures/azure/capz-azure-cluster-identity.yaml
  tests/cypress/latest/fixtures/azure/capz-helm-values-secret.yaml
  tests/cypress/latest/fixtures/azure/capz-kubeadm-class-cluster.yaml
  tests/cypress/latest/fixtures/azure/capz-rke2-class-cluster.yaml
  tests/cypress/latest/fixtures/capi-kubeadm-provider.yaml
  tests/cypress/latest/fixtures/docker/capd-helm-values.yaml
  tests/cypress/latest/fixtures/gcp/capg-helm-values-secret.yaml
  tests/cypress/latest/fixtures/gcp/capg-kubeadm-class-cluster.yaml
  tests/cypress/latest/fixtures/vsphere/capi-vsphere-provider.yaml
  tests/cypress/latest/fixtures/vsphere/capv-docker-auth-token-secret.yaml
  tests/cypress/latest/fixtures/vsphere/capv-helm-values-secret.yaml
  tests/cypress/latest/fixtures/vsphere/capv-helm-values.yaml
  tests/cypress/latest/fixtures/vsphere/capv-kube-vip-static-pod-toggle-job.yaml
  tests/cypress/latest/fixtures/vsphere/capv-vsphere-cluster-identity.yaml
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/capz_support.ts
  tests/cypress/latest/support/commands.ts
  tests/scripts/start-cypress-tests
Labels: kind/enhancement, area/testing, squad/qa
