Repository rancher/rancher-turtles-e2e, pull requests merged in 2025-04, with the labels that each got.

#153 Apps installation and repos handling improvements
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
Labels: kind/bug, area/testing

#158 Switch capi-ui repo to https instead of git
  tests/cypress/latest/e2e/unit_tests/turtles_extension.spec.ts
  tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
Labels: kind/bug, kind/enhancement

#169 Change branch to main for AKS cluster tests
  tests/cypress/latest/e2e/unit_tests/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_rke2_clusterclass.spec.ts
Labels: squad/qa

#171 Provider versions bump after release v0.19.0-rc.1
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Labels: squad/qa

#174 release-2.10 branch refactor
  .github/workflows/ui-e2e.yaml
  tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capa_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_clusterclass_ui_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capg_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capv_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_cluster.spec.ts
Labels: squad/qa
