Repository rancher/rancher-turtles-e2e, pull requests merged in 2025-09, with the labels that each got.

#264 Bump Providers
  tests/cypress/latest/e2e/providers_setup.spec.ts
Labels: area/ci, squad/qa, kind/chore

#259 Add support for Rancher 2.12
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
  tests/cypress/latest/cypress.config.ts
  tests/cypress/latest/e2e/capa_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/providers_setup.spec.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
  tests/scripts/start-cypress-tests
Labels: kind/enhancement

#269 Npm update qase
  .github/workflows/linter.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
  tests/Makefile
  tests/cypress/latest/.eslintrc.json
  tests/cypress/latest/cypress.config.ts
  tests/cypress/latest/e2e/azure_rke2_v2prov_cluster.spec.ts
  tests/cypress/latest/e2e/capa_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_kubeadm_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capd_rke2_upgrade_clusterclass.spec.ts
  tests/cypress/latest/e2e/capg_kubeadm_clusterclass.spec.ts
  tests/cypress/latest/e2e/capv_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/capz_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/legacy/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capa_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capa_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capz_aks_cluster.spec.ts
  tests/cypress/latest/e2e/legacy/capz_aks_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/providers_setup.spec.ts
  tests/cypress/latest/e2e/turtles_chart.spec.ts
  tests/cypress/latest/e2e/turtles_ui_extension.spec.ts
  tests/cypress/latest/eslint.config.mjs
  tests/cypress/latest/package.json
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/e2e.ts
  tests/e2e/helpers/qase/helper_qase.go
  tests/scripts/start-cypress-tests
Labels: squad/qa, dependencies

#286 Add turtles-chart selector
  tests/cypress/latest/support/commands.ts
Labels: kind/enhancement, squad/qa

#297 Fix TS support for tags in it() and describe()
  tests/cypress/latest/package.json
  tests/cypress/latest/tsconfig.json
Labels: squad/qa
