Repository rancher/rancher-turtles-e2e, pull requests merged in 2025-05, with the labels that each got.

#176 Remove checking Enable Agent TLS Mode; it is now enabled by default
  tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: squad/qa

#179 Always refresh repo after adding
  tests/cypress/latest/support/commands.ts
Labels: kind/bug, squad/qa

#185 Use upstream docker lb-config
  tests/assets/rancher-turtles-fleet-example/capd/rke2/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capd/rke2/clusters/templates/cluster.yaml
  tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
Labels: kind/bug, area/ci, squad/qa

#186 Align Qase Ids & Refactor specs
  .github/workflows/janitor.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
  README.md
  tests/assets/rancher-turtles-fleet-example/capa/rke2/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capa/rke2/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capz/aks/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capz/aks/class-clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capz/aks/clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capz/aks/clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capz/rke2/class-clusters/templates/cluster.yaml
  tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_ui_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_aks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/providers_setup.spec.ts
  tests/cypress/latest/e2e/unit_tests/turtles_extension.spec.ts
  tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
  tests/cypress/latest/fixtures/capz-helm-values-secret.yaml
  tests/cypress/latest/package.json
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/capz_support.ts
  tests/cypress/latest/support/e2e.ts
  tests/scripts/start-cypress-tests
Labels: area/ci, squad/qa, kind/chore

#187 Revert branch - main
  tests/cypress/latest/e2e/unit_tests/capa_eks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capa_rke2_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_kubeadm_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capd_rke2_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capg_gke_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_aks_cluster.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_aks_clusterclass.spec.ts
  tests/cypress/latest/e2e/unit_tests/capz_rke2_clusterclass.spec.ts
Labels: squad/qa

#194 AWS Kubeadm Cluster tests
  .github/workflows/master-e2e.yaml
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/.helmignore
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/Chart.yaml
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/fleet.yaml
  tests/assets/rancher-turtles-fleet-example/capa/kubeadm/clusters/templates/cluster.yaml
  tests/assets/rancher-turtles-fleet-example/capv/kubeadm/class-clusters/values.yaml
  tests/cypress/latest/e2e/unit_tests/capa_kubeadm_cluster.spec.ts
Labels: kind/enhancement, area/testing, squad/qa
